# Generated by Django 5.0.6 on 2024-06-15 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Link',
                'verbose_name_plural': 'Verification Links',
                'db_table': 'verification',
                'indexes': [models.Index(fields=['user'], name='verificatio_user_id_20892e_idx')],
            },
        ),
    ]
