# Generated by Django 5.0.6 on 2024-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verificationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/default.png', null=True, upload_to='user_photos'),
        ),
    ]
