# Generated by Django 5.0.6 on 2024-06-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='owner',
        ),
        migrations.AlterField(
            model_name='filepermissionmodel',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='filesharing.filemodel'),
        ),
    ]
