# Generated by Django 5.0.6 on 2024-06-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0002_remove_filemodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermissionmodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='filesharing.filemodel'),
        ),
    ]
