# Generated by Django 5.0.6 on 2024-06-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0004_remove_filemodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='cloud_name',
            new_name='id',
        ),
    ]
