# Generated by Django 5.0.6 on 2024-06-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0008_alter_filepermissionmodel_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermissionmodel',
            name='permission',
        ),
    ]
