# Generated by Django 5.0.6 on 2024-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0009_remove_filepermissionmodel_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepermissionmodel',
            name='permission',
            field=models.CharField(choices=[('R', 'Read Permission'), ('F', 'Full Permission')], default='F', max_length=10),
            preserve_default=False,
        ),
    ]
